const pdfStyles = {
  body: {
    backgroundColor: '#f5f5f5',
    padding: 20,
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 20,
  },
  infoHeader: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'Poppins-Medium',
    backgroundColor: '#373D3E',
    padding: 5,
    color: '#FFF',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
  },
  infoHeaderContent: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontFamily: 'Poppins-Medium',
    backgroundColor: '#366FB4',
    color: '#FFF',
    fontSize: 14,
    paddingTop: 5,
    paddingBottom: 5,
    paddingRight: 10,
    paddingLeft: 10,
  },
  infoHeaderContentText: {
    fontSize: 12,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  contentHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    fontFamily: 'Poppins-Bold',
    backgroundColor: '#373D3E',
    padding: 5,
    color: '#FFF',
    fontSize: 14,
  },
  ticketsContainer: {
    backgroundColor: '#366FB4',
    padding: 10,
  },
  ticketHeader: {
    backgroundColor: '#FFF',
    color: '#000',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontFamily: 'Poppins-Medium',
    fontSize: 10,
    padding: 5,
  },
  ticketSubject: {
    fontFamily: 'Poppins-Medium',
    color: '#FFF',
    backgroundColor: '#373D3E',
    padding: 5,
    fontSize: 12,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  ticketMessage: {
    display: 'flex',
    flexDirection: 'column',
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 20,
    paddingLeft: 20,
    backgroundColor: '#FFF',
    marginBottom: 20,
  },
};

export default pdfStyles;
